name: Sync LeetCode

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Sync LeetCode
        uses: Mengqi97/leetcode-sync@v1
        with:
          username: ${{ secrets.LEETCODE_USERNAME }}
          password: ${{ secrets.LEETCODE_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
